- Pipfile.lock
- thoth/metrics_exporter/__init__.py
- thoth/metrics_exporter/config.py
- thoth/metrics_exporter/jobs.py
> added JanusGraph Vertex, Edge count

- Pipfile
- Pipfile.lock
Related: https://github.com/thoth-station/kebechet/issues/209
> Use standardized Python package name to fix issues in Kebechet

- app.py
- thoth/metrics_exporter/__init__.py
- thoth/metrics_exporter/jobs.py
Depends-On: https://github.com/thoth-station/storages/pull/579
> New metrics to observe the content of Thoth Graph database

- thoth/metrics_exporter/jobs.py
Depends-On: https://github.com/thoth-station/storages/pull/598
Relates: https://github.com/thoth-station/storages/pull/604
> Fix typo in argument and variable name

- Pipfile
- app.py
- thoth/metrics_exporter/__init__.py
- thoth/metrics_exporter/jobs.py
- Modified the metrics to be consistent with Dgraph new functions created (https://github.com/thoth-station/storages/pull/662)
- Changed old text related to Janusgraph
- Deleted obsolete and duplicate metrics
> Modified metrics for Dgraph

- app.py
- thoth/metrics_exporter/__init__.py
- thoth/metrics_exporter/jobs.py
linked to https://github.com/thoth-station/storages/pull/702
> Update functions for new schema and add new metrics

- openshift/deployment-template.yaml
To Pull images from a different namespace.
> added namespace to deployment trigger

- .zuul.yaml
> fixed webhhok url

- openshift/deployment-template.yaml
- thoth/metrics_exporter/jobs.py
Set all namespace that Thoth team wants to monitor.
> Explicitly set all namespaces

- thoth/metrics_exporter/jobs.py
> Correct duplicate

- thoth/metrics_exporter/jobs.py
> Changed inizialization of jobs

- thoth/metrics_exporter/jobs.py
> Added two new job status

- thoth/metrics_exporter/jobs.py
New status added. Fixes: https://github.com/thoth-station/metrics-exporter/issues/68
> Add new status

- openshift/deployment-template.yaml
- thoth/metrics_exporter/jobs.py
> New environments variables to monitor AMUN namespaces

- openshift/deployment-template.yaml
- thoth/metrics_exporter/jobs.py
- thoth/metrics_exporter/metrics.py
> Created metrics to monitor Ceph results

- thoth/metrics_exporter/jobs.py
Added PackageAnalysisResultStore to monitor results in Ceph.
> Added PackageAnalysisResultStore

- thoth/metrics_exporter/jobs.py
- thoth/metrics_exporter/metrics.py
Depends-On: https://github.com/thoth-station/storages/pull/852#issuecomment-516428234
> Created metrics for PI

- thoth/metrics_exporter/jobs.py
- thoth/metrics_exporter/metrics.py
Depends-On: https://github.com/thoth-station/storages/pull/890
> Introduce metrics for unsolved Python packages count

- openshift/deployment-template.yaml
Fixes: https://github.com/thoth-station/metrics-exporter/issues/106
Related: https://github.com/thoth-station/metrics-exporter/pull/105
> Provide infra namespace to list installed solvers

- thoth/metrics_exporter/jobs.py
- thoth/metrics_exporter/metrics.py
Generalized metrics for jobs.
Depends-On: https://github.com/thoth-station/common/pull/450
> Generalized metrics for Jobs

- thoth/metrics_exporter/jobs.py
- thoth/metrics_exporter/metrics.py
> Do not count total nodes with recent transition to relational db

- thoth/metrics_exporter/jobs.py
Let's error out all the metrics if there is a connection error and check for
connection errors explicitly in a separate metrics job.
> Simplify metrics error handling for graphdb and ceph connection errors

- thoth/metrics_exporter/jobs.py
> Add job label to monitor solver jobs

- thoth/metrics_exporter/jobs.py
> Fix listing of functions for registered jobs

- thoth/metrics_exporter/jobs.py
> All jobs and configmaps standardized

- wsgi.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/147
> Print Metrics Exporter version on startup

- wsgi.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/151
> Correct import class name

- thoth/metrics_exporter/jobs.py
- wsgi.py
* simplify registering methods for gathering metrics
* use typing (preparation for mypy checks)
> Simplify registering a job

- thoth/metrics_exporter/jobs/db.py
> Fix import statement

- thoth/metrics_exporter/jobs/adviser.py
- thoth/metrics_exporter/jobs/db.py
- thoth/metrics_exporter/jobs/inspection.py
- thoth/metrics_exporter/jobs/pi.py
- thoth/metrics_exporter/jobs/python.py
- thoth/metrics_exporter/jobs/software_environment.py
- thoth/metrics_exporter/jobs/user.py
Depends-On: https://github.com/thoth-station/storages/pull/1188
> Update queries according to new naming convention

- thoth/metrics_exporter/jobs/adviser.py
- thoth/metrics_exporter/jobs/inspection.py
- thoth/metrics_exporter/jobs/solver.py
- thoth/metrics_exporter/jobs/user.py
Depends-On: https://github.com/thoth-station/storages/issues/1217
> Use enums in queries to the database

- Pipfile
- Pipfile.lock
- wsgi.py
> added CORS headers and allow from all

- wsgi.py
See: https://apscheduler.readthedocs.io/en/latest/userguide.html#missed-job-executions-and-coalescing
> Enable coalescing in jobs executed

- thoth/metrics_exporter/jobs/openshift.py
This new implementation avoids checking for Jobs or ConfigMaps in a namespace which cannot have specific services by core implementation (https://raw.githubusercontent.com/thoth-station/core/master/doc/architecture.png).
> Optimize queries for jobs and configmaps

- thoth/metrics_exporter/jobs/pi.py
Depends-On: https://github.com/thoth-station/storages/pull/1273
> Adjust metrics to report 0 if no frameworks from inspections found in the database

- thoth/metrics_exporter/jobs/solver.py
> Fix logging error produced when showing results

- Pipfile
- Pipfile.lock
Related: https://github.com/thoth-station/common/pull/539
> Add sentry-sdk[flask] and aiocontextvars for Sentry integrations

- thoth/metrics_exporter/jobs/python.py
- thoth/metrics_exporter/jobs/solver.py
- thoth/metrics_exporter/metrics.py
> Adjust and create metrics to monitor multiple solvers

- Pipfile
- Pipfile.lock
- openshift/deployment-template.yaml
- thoth/metrics_exporter/jobs/solver.py
- thoth/metrics_exporter/metrics.py
Depends-On: https://github.com/thoth-station/storages/pull/1387
- Added metrics that will be used to create SLI for Thoth
> New query for Python Packages

- thoth/metrics_exporter/jobs/solver.py
> Correct variable

- thoth/metrics_exporter/jobs/solver.py
> Introduce safe check

- thoth/metrics_exporter/jobs/solver.py
- thoth/metrics_exporter/metrics.py
> Adjust Counter

- openshift/deployment-template.yaml
- thoth/metrics_exporter/jobs/adviser.py
- thoth/metrics_exporter/jobs/common.py
- thoth/metrics_exporter/jobs/inspection.py
- thoth/metrics_exporter/jobs/solver.py
- thoth/metrics_exporter/metrics.py
- Created solver latency SLI (Histogram Prometheus metric)
- Created adviser latency SLI (Histogram Prometheus metric)
- Created inspection latency SLI (Histogram Prometheus metric)
These SLI are based on Argo workflow metrics.
> New Thoth SLI

- thoth/metrics_exporter/jobs/pi.py
- thoth/metrics_exporter/metrics.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/294
Depends-On: https://github.com/thoth-station/storages/pull/1525
> Adjust metrics for PI

- thoth/metrics_exporter/jobs/openshift.py
- thoth/metrics_exporter/metrics.py
Depends-On: https://github.com/thoth-station/common/pull/663
> Metrics for imagestreams

- thoth/metrics_exporter/jobs/openshift.py
> Correct variables

- thoth/metrics_exporter/jobs/adviser.py
- thoth/metrics_exporter/metrics.py
> Qeb-Hwt App SLI

- thoth/metrics_exporter/jobs/adviser.py
- thoth/metrics_exporter/jobs/inspection.py
- thoth/metrics_exporter/jobs/solver.py
> Use same time in evaluation of LSI 

- thoth/metrics_exporter/jobs/adviser.py
- thoth/metrics_exporter/jobs/common.py
- thoth/metrics_exporter/metrics.py
> Qeb-Hwt SLI for quality

- thoth/metrics_exporter/jobs/db.py
- thoth/metrics_exporter/metrics.py
> Metric for bloat data for the database

- thoth/metrics_exporter/jobs/openshift.py
> Reduce logs

- thoth/metrics_exporter/jobs/openshift.py
> Less less logs

- thoth/metrics_exporter/metrics.py
> Reduce bucket size for GitHub App workflows

- thoth/metrics_exporter/jobs/db.py
> Use float for timestamps

- thoth/metrics_exporter/jobs/common.py
> Monitor workflows in pending state

- thoth/metrics_exporter/jobs/solver.py
> Wrong namespace to be monitored for solver workflows metric

- thoth/metrics_exporter/metrics.py
> Increase time for successful adviser

- openshift/deployment-template.yaml
> Correct-info

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/major-release.md
- .github/ISSUE_TEMPLATE/minor-release.md
- .github/ISSUE_TEMPLATE/patch-release.md
- .github/PULL_REQUEST_TEMPLATE.md
> updates the GitHub templates

- thoth/metrics_exporter/jobs/__init__.py
- thoth/metrics_exporter/jobs/adviser.py
- thoth/metrics_exporter/jobs/argo_workflows.py
- thoth/metrics_exporter/jobs/inspection.py
- thoth/metrics_exporter/jobs/openshift.py
- thoth/metrics_exporter/jobs/solver.py
- thoth/metrics_exporter/jobs/utils.py
- thoth/metrics_exporter/metrics.py
Add new class of metrics for Argo workflows
> Add argo workflows class of metrics

- thoth/metrics_exporter/jobs/ceph.py
Use count documents method from Thoth storages
> use count method for Ceph documents

- thoth/metrics_exporter/jobs/__init__.py
- thoth/metrics_exporter/jobs/adviser.py
- thoth/metrics_exporter/jobs/analysis.py
- thoth/metrics_exporter/jobs/base.py
- thoth/metrics_exporter/jobs/ceph.py
- thoth/metrics_exporter/jobs/db.py
- thoth/metrics_exporter/jobs/dependency_monkey.py
- thoth/metrics_exporter/jobs/inspection.py
- thoth/metrics_exporter/jobs/package_analysis.py
- thoth/metrics_exporter/jobs/provenance.py
- thoth/metrics_exporter/jobs/solver.py
- thoth/metrics_exporter/metrics.py
- Split metrics to reduce time to evaluate
- Delete metrics not useful
> Split metrics to reduce time to evaluate

- Pipfile
- Pipfile.lock
- thoth/metrics_exporter/jobs/__init__.py
- thoth/metrics_exporter/jobs/pypi.py
- thoth/metrics_exporter/metrics.py
Introduce metric from PyPI statistics
> Add metrics from Pypi

- openshift/buildConfig-template.yaml
- thoth/metrics_exporter/configuration.py
- thoth/metrics_exporter/jobs/adviser.py
- thoth/metrics_exporter/jobs/inspection.py
- thoth/metrics_exporter/jobs/solver.py
- Add imports and remove old imports
- Adjust issues with PrometheusConnect
> Missing import

- thoth/metrics_exporter/jobs/python.py
- thoth/metrics_exporter/jobs/solver.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/461
https://github.com/thoth-station/metrics-exporter/issues/460
https://github.com/thoth-station/metrics-exporter/issues/464
Fixes:
Fix issues
> Correct errors

- pyproject.toml
- thoth/metrics_exporter/jobs/python.py
- thoth/metrics_exporter/jobs/solver.py
Fixes: #461 #468 
- corrected use of normalize_python_index_url function
- corrected use of parse_python_solver_name function
update module based upon storages and common functions
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
> update module based upon storages and common functions

- .thoth.yaml
> Add maintainer

- thoth/metrics_exporter/jobs/__init__.py
- thoth/metrics_exporter/jobs/base.py
- thoth/metrics_exporter/jobs/ceph.py
- thoth/metrics_exporter/jobs/security.py
- thoth/metrics_exporter/metrics.py
Related-To: https://github.com/thoth-station/metrics-exporter/issues/474
Depends-On: https://github.com/thoth-station/storages/pull/1987
Add metrics for Security Indicators
> Add SI metrics

- Pipfile.lock
Use latest storages to have new release
> Bump version for release with new SI metrics

- thoth/metrics_exporter/metrics.py
> Adjust metrics to start with Thoth

- thoth/metrics_exporter/jobs/security.py
- thoth/metrics_exporter/metrics.py
> Introduce metric on SI Python packages not analyzable

- thoth/metrics_exporter/jobs/db.py
> Adjust datatype

- thoth/metrics_exporter/jobs/kebechet.py
Dependent on - https://github.com/thoth-station/storages/pull/2141
> Changed func name

- Pipfile.lock
- thoth/metrics_exporter/jobs/adviser.py
- thoth/metrics_exporter/metrics.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/549
> Introduce metrics for unique usage of adviser integrations

- thoth/metrics_exporter/jobs/db.py
- thoth/metrics_exporter/metrics.py
Related: https://github.com/thoth-station/storages/issues/1885
Depends on: https://github.com/thoth-station/storages/pull/2105
API call to storages to export corruption metric
> add job to check for db corruption

- OWNERS
- thoth/metrics_exporter/jobs/db.py
- thoth/metrics_exporter/metrics.py
> remove-metric

- thoth/metrics_exporter/jobs/db.py
None in revision should never appear
> Add check if database is not connected when get method to retrieve alembic version from table is used.

- thoth/metrics_exporter/jobs/db.py
- Adjust one metrics missing a label
- Adjust condition to keep/exclude metrics
> Adjust condition to keep metrics

- .github/ISSUE_TEMPLATE/kebechet-info.md
- .github/ISSUE_TEMPLATE/kebechet_update.md
> Add Kebechet templates

- thoth/metrics_exporter/jobs/user.py
Related-To: https://github.com/thoth-station/storages/pull/2217/files
Fix query used in get_user_python_software_stack_count method due to changes in thoth-storages
> Fix query used in get_user_python_software_stack_count method

- thoth/metrics_exporter/jobs/solver.py
- thoth/metrics_exporter/metrics.py
Related-To: https://github.com/thoth-station/metrics-exporter/issues/586
> Add check on number of solvers from CM and from database

- thoth/metrics_exporter/jobs/db.py
- thoth/metrics_exporter/metrics.py
Related: https://github.com/thoth-station/storages/pull/2230/
> Introduce a metric for obtaining the current database size

- .pre-commit-config.yaml
- .prow.yaml
- thoth/metrics_exporter/jobs/db.py
- thoth/metrics_exporter/jobs/solver.py
- thoth/metrics_exporter/jobs/user.py
- thoth/metrics_exporter/metrics.py
- :sparkles: autoupdate of pre-commit-config
- :pencil: pre-commit did some reformatting
n/a
just some standard minor changes
> formatting updates

- thoth/metrics_exporter/jobs/base.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/630
> Solve type checking

- Pipfile
- Pipfile.lock
- README.md
- thoth/metrics_exporter/__init__.py
- thoth/metrics_exporter/jobs/__init__.py
- thoth/metrics_exporter/jobs/base.py
- thoth/metrics_exporter/jobs/db.py
- thoth/metrics_exporter/jobs/kafka.py
- thoth/metrics_exporter/jobs/security.py
- thoth/metrics_exporter/jobs/solver.py
- thoth/metrics_exporter/metrics.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/627
Fixes: https://github.com/thoth-station/metrics-exporter/issues/625
Fixes: https://github.com/thoth-station/thoth-application/issues/416
Related-To: https://github.com/thoth-station/thoth-application/issues/854
- Introduce Kafka metrics
- Adjust metrics run at the beginning
> Check initial connections and add Kafka metrics

- thoth/metrics_exporter/jobs/db.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/661
> Set a different values for errors, not -1

- thoth/metrics_exporter/jobs/ceph.py
- thoth/metrics_exporter/jobs/kafka.py
- thoth/metrics_exporter/metrics.py
Related-To: https://github.com/thoth-station/thoth-application/issues/854
> Use convention for alarms

- .aicoe-ci.yaml
> Update base image

- thoth/metrics_exporter/jobs/db.py
- thoth/metrics_exporter/metrics.py
Related-To: https://github.com/thoth-station/metrics-exporter/issues/704
Remove metric that are migrated to graph-metrics-exporter
> Remove long running metric

- thoth/metrics_exporter/metrics.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/714
> missin definition of metric

- thoth/metrics_exporter/jobs/adviser.py
> Use common enums

- thoth/metrics_exporter/jobs/adviser.py
- thoth/metrics_exporter/jobs/base.py
- thoth/metrics_exporter/jobs/db.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/181
> Do not set metrics unless schema is up 2 date

- thoth/metrics_exporter/jobs/__init__.py
- thoth/metrics_exporter/jobs/kebechet.py
- thoth/metrics_exporter/metrics.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/559
> Introduce metric on number of users of kebechet per manager

- Pipfile
- Pipfile.lock
- thoth/metrics_exporter/configuration.py
- thoth/metrics_exporter/jobs/kebechet.py
- thoth/metrics_exporter/metrics.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/705
Add Kebechet rate limit metric.
> Introduce Kebechet rate limit metric

- README.md
> Add container info in README

- Pipfile
- Pipfile.lock
> Remove development dependencies

- thoth/metrics_exporter/jobs/security.py
- thoth/metrics_exporter/jobs/solver.py
> Fix label for retrieving metrics

- README.rst
> Small README fixes

- thoth/metrics_exporter/jobs/db.py
- thoth/metrics_exporter/metrics.py
Related to https://github.com/thoth-station/metrics-exporter/issues/822
Replaces https://github.com/thoth-station/metrics-exporter/pull/836
- No
> Register metric for datetime of last container image analysis synced in the database

- .pre-commit-config.yaml
- .thoth.yaml
- pyproject.toml
- wsgi.py
HouseKeeping: Updated pre-commit and thoth.yaml
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
> :recycle: HouseKeeping: Updated pre-commit and thoth.yaml
