thoth-station/metrics-exporter

Pipfile.lock
PR fixes the build-fail.
- metrics-exporter build failed due to non updated Pipfile.lock file.
=> updated pipfile-lock

openshift/deployment-template.yaml
... so that metrics-exporter can spend more time on CPU when aggregating
metrics
=> Increase resources for metrics-exporter

openshift/deployment-template.yaml
This should help removing "gaps" we see in graph during rolling deployments in
the cluster.
=> Provide readiness and liveness probes

openshift/deployment-template.yaml
changed sa from thoth-ops to metrics-exporter
- To maintain consistency the service account has been modified to metrics-exporter.
-  Already updated in **stage** environment.
Rolebinding needed:
- thoth-frontend-stage
- thoth-middletier-stage
- thoth-backend-stage
- thoth-amun-api-stage
- thoth-amun-inspection-stage
Already updated in **stage** environment.
Related-to: https://github.com/thoth-station/thoth-ops/issues/68
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
=> changed sa from thoth-ops to metrics-exporter

thoth/metrics_exporter/jobs.py, thoth/metrics_exporter/metrics.py
Added metrics to check inspections in Ceph per identifier (if any).
Example:
```
- thoth_inspection_results_ceph{identifier="without_identifier"} 2264.0
- thoth_inspection_results_ceph{identifier="20k_test"} 300.0
- thoth_inspection_results_ceph{identifier="dataset"} 5678.0
- thoth_inspection_results_ceph{identifier="last_test"} 1.0
- thoth_inspection_results_ceph{identifier="test_name"} 1.0 #
```
=> Added metrics to check inspections in Ceph per identifier (if any)

wsgi.py
Debug mode can be turned on by setting environment variable `THOTH_LOG_METRICS__EXPORTER` to `DEBUG`.
=> Remove unused debug variable

thoth/metrics_exporter/jobs/solver.py, thoth/metrics_exporter/metrics.py
As @fridex pointed out, in Grafana the metric that counts `total number of solved packages with no error` went below 0. This is because that metric is evaluated as difference between two metrics which are evaluated randomly. In certain circumstances, like when lot of solver are run, the metric subtracted can be evaluated before the other and therefore can have a value higher. The stability is reached after solver finished and a new equilibrium is reached. 
This PR evaluate this metric directly in 'metrics-exporter', therfore it avoid that situation, because both metrics that make `total number of solved packages with no error` are evaluated at the same time.
=> Created metrics to avoid 'race conditions'

openshift/deployment-template.yaml
To guarantee smooth metrics on rolling deployments, metrics-exporter reports
503 until all the metrics are obtained. As we have a lot of data in the
cluster, metrics-exporter fails to obtain metrics in the given time and
deployment fails.
=> Give metrics-exporter more time to boot

wsgi.py
If there is raised an exception in any metrics method, the increment is not
performed and service does not become available.
=> Increment metrics evaluation counter each time a metrics method is called

thoth/metrics_exporter/jobs/solver.py
In this way the first initialization does not instantiate the metric until the second one is not instantiated. There would be an error in the first data collected otherwise.
=> Adjust time initialization of the metric

thoth/metrics_exporter/__init__.py, thoth/metrics_exporter/metrics.py, wsgi.py
so that we can have Kebechet bound versions, but also have an extended version to include dependencies version
https://github.com/thoth-station/metrics-exporter/issues/363
=> added a service_version

thoth/metrics_exporter/jobs/base.py
I saw few errors related to an unconnected adapter. This change makes sure that even if adapter is already instantiated, the connection is eventually reestablished if adapter was disconnected.
=> Connect if the adapter is not connected

Pipfile.lock, thoth/metrics_exporter/jobs/adviser.py, thoth/metrics_exporter/metrics.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/480
Add metric for Thoth Integrations SLI.
```
thoth_graphdb_adviser_count_per_source_type{thoth_integration="CLI"} 71.0 
thoth_graphdb_adviser_count_per_source_type{thoth_integration="KEBECHET"} 0.0 
thoth_graphdb_adviser_count_per_source_type{thoth_integration="S2I"} 0.0 
thoth_graphdb_adviser_count_per_source_type{thoth_integration="GITHUB_APP"} 154.0 
thoth_graphdb_adviser_count_per_source_type{thoth_integration="JUPYTER_NOTEBOOK"} 0.0 
```
=> Introduce metrics for Thoth integrations

Pipfile, Pipfile.lock, thoth/metrics_exporter/__init__.py, thoth/metrics_exporter/jobs/db.py, thoth/metrics_exporter/metrics.py
Create a metric for a Prometheus alarm when thoth-storages used in management-API is not the latest one
```
```
deployment requires new env variable: `MANAGEMENT_API_PROMETHEUS_INSTANCE`
=> Introduce metric for alarm on storages version in management-API

thoth/metrics_exporter/jobs/solver.py, thoth/metrics_exporter/metrics.py
Related-To: https://github.com/thoth-station/metrics-exporter/issues/586
Introduce metrics on number of solvers identified from Ecosystem Solver database table
Metric for number of solvers from CM already exists and it is the default to verify number of packages solved per solver.
=> Introduce metric for number of solvers from database table

thoth/metrics_exporter/jobs/db.py, thoth/metrics_exporter/metrics.py
Related-To: https://github.com/thoth-station/metrics-exporter/issues/573
```
thoth_graphdb_alembic_version_rows Number of rows in alembic version table.
```
=> Add almebic rows table metric

thoth/metrics_exporter/jobs/security.py, thoth/metrics_exporter/metrics.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/174
Add metric on number of CVE.
```
```
=> Add CVE metric

thoth/metrics_exporter/jobs/db.py
```
{"name": "thoth.metrics_exporter", "levelname": "ERROR", "module": "wsgi", "lineno": 89, "funcname": "func_wrapper", "created": 1625066211.2252166, "asctime": "2021-06-30 15:16:51,225", "msecs": 225.21662712097168, "relative_created": 24910.18319129944, "process": 23, "message": "Failed to run metrics gathering job DBMetrics.check_is_schema_up2date_for_components\nTraceback (most recent call last):\n  File \"/opt/app-root/src/wsgi.py\", line 87, in func_wrapper\n    job()\n  File \"/opt/app-root/lib64/python3.8/site-packages/decorator.py\", line 232, in fun\n    return caller(func, *(extras + args), **kw)\n  File \"/opt/app-root/src/thoth/metrics_exporter/jobs/base.py\", line 42, in register_metric_job\n    method(*args, …
```
=> Add missing labels

thoth/metrics_exporter/jobs/security.py, thoth/metrics_exporter/metrics.py
Related: https://github.com/thoth-station/storages/pull/2460
Related: https://github.com/thoth-station/adviser/issues/2142
With this information, we will be able to see when CVEs from PyPA/advisory-db were last updated.
=> Introduce a metric for number of days since the last CVE update

Pipfile, Pipfile.lock, thoth/metrics_exporter/jobs/security.py, thoth/metrics_exporter/metrics.py
Related: https://github.com/thoth-station/metrics-exporter/pull/784
Depends-On: https://github.com/thoth-station/metrics-exporter/pull/784
Similarly, as we do for CVEs from PyPA/advisory-db, we track timestamp for container image analyses done in Quay. This metric shows the number of days since the last update was done. It might be a good idea to expose this metric and alarm if the update was not done for some time, making sure users have fresh data.
=> Quay security timestamp

thoth/metrics_exporter/jobs/kebechet.py, thoth/metrics_exporter/metrics.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/791
=> introduce metrics for software stacks maintained by Kebechet

thoth/metrics_exporter/jobs/db.py, thoth/metrics_exporter/metrics.py
Related to #822 
- No
Register a metric to get the datetime of the last solver run synced in the database
=> Register metric to get datetime of last solver synced in database

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .pre-commit-config.yaml, .prow.yaml
Update the GitHub issue templates using the ones from the template project.
The main need here was to switch the default issue label to `needs-triage` instead of `triage/needs-information` (the latter is to be added after a review that detects missing information), and the removal of the Yes/No check-box style from #840.
Also taking the opportunity to update pre-commit plugins
=> Update GitHub templates and pre-commit plugin versions

.pre-commit-config.yaml
Github removed support for the git:// protocol some times ago.
This avoids setup of a local environment failing.
Black 22.1.0 fails due to some missing dependency, align it with other
repos.
=> Fix .pre-commit-config.yaml
